name: tag

on:
  schedule:
    - cron: '*/1 * * * *'  # Runs every minute for testing
  workflow_dispatch:
    inputs:
      reference:
        description: 'Branch Name'
        required: false

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up skopeo and jq
      run: |
        sudo apt-get update
        sudo apt-get install -y skopeo jq

    - name: Execute script with branch parameter
      env:
        BRANCH_NAME: ${{ github.event.inputs.reference || 'latest' }}
      run: |
        echo "Executing script with branch name: $BRANCH_NAME"
        chmod +x ./tag.sh
        ./tag.sh "$BRANCH_NAME"
